# Generated by Django 5.2.4 on 2025-08-03 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdminUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        db_index=True, max_length=50, unique=True, verbose_name="用户名"
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="密码哈希")),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        null=True,
                        verbose_name="邮箱",
                    ),
                ),
                (
                    "real_name",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="真实姓名"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否激活"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(default=False, verbose_name="是否超级管理员"),
                ),
                (
                    "last_login_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="最后登录时间",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "管理员",
                "verbose_name_plural": "管理员",
                "db_table": "admin_users",
                "indexes": [
                    models.Index(
                        fields=["username"], name="admin_users_usernam_8a6e5b_idx"
                    ),
                    models.Index(fields=["email"], name="admin_users_email_91b518_idx"),
                    models.Index(
                        fields=["last_login_at"], name="admin_users_last_lo_83b654_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AdminLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("approve", "审核通过"),
                            ("reject", "审核拒绝"),
                            ("delete", "删除"),
                            ("login", "登录"),
                            ("logout", "登出"),
                            ("create", "创建"),
                            ("update", "更新"),
                        ],
                        db_index=True,
                        max_length=50,
                        verbose_name="操作类型",
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("post", "分享"),
                            ("user", "用户"),
                            ("admin", "管理员"),
                        ],
                        max_length=20,
                        verbose_name="目标类型",
                    ),
                ),
                ("target_id", models.IntegerField(verbose_name="目标ID")),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="操作描述"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP地址"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="用户代理"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admin_panel.adminuser",
                        verbose_name="管理员",
                    ),
                ),
            ],
            options={
                "verbose_name": "管理操作日志",
                "verbose_name_plural": "管理操作日志",
                "db_table": "admin_logs",
                "indexes": [
                    models.Index(
                        fields=["admin"], name="admin_logs_admin_i_d23260_idx"
                    ),
                    models.Index(
                        fields=["action"], name="admin_logs_action_ff7830_idx"
                    ),
                    models.Index(
                        fields=["target_type", "target_id"],
                        name="admin_logs_target__bd5226_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="admin_logs_created_3ee9bc_idx"
                    ),
                ],
            },
        ),
    ]
