# Generated by Django 5.2.4 on 2025-08-03 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shop_name",
                    models.CharField(max_length=100, verbose_name="店铺名称"),
                ),
                (
                    "shop_location",
                    models.CharField(max_length=200, verbose_name="店铺地址"),
                ),
                ("shop_price", models.IntegerField(verbose_name="人均消费")),
                ("comment", models.TextField(verbose_name="推荐理由")),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=10,
                        null=True,
                        verbose_name="纬度",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=11,
                        null=True,
                        verbose_name="经度",
                    ),
                ),
                (
                    "location_address",
                    models.CharField(
                        blank=True, max_length=300, null=True, verbose_name="位置地址"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待审核"),
                            ("approved", "已展示"),
                            ("rejected", "已拒绝"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="审核状态",
                    ),
                ),
                (
                    "likes_count",
                    models.IntegerField(
                        db_index=True, default=0, verbose_name="点赞数"
                    ),
                ),
                ("view_count", models.IntegerField(default=0, verbose_name="查看数")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.user",
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "社区分享",
                "verbose_name_plural": "社区分享",
                "db_table": "posts",
            },
        ),
        migrations.CreateModel(
            name="PostImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_url", models.URLField(max_length=500, verbose_name="图片地址")),
                (
                    "sort_order",
                    models.IntegerField(
                        db_index=True, default=0, verbose_name="排序顺序"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="community.post",
                        verbose_name="分享",
                    ),
                ),
            ],
            options={
                "verbose_name": "分享图片",
                "verbose_name_plural": "分享图片",
                "db_table": "post_images",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="PostLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="community.post",
                        verbose_name="分享",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.user",
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "分享点赞",
                "verbose_name_plural": "分享点赞",
                "db_table": "post_likes",
            },
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["user"], name="posts_user_id_05c508_idx"),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["status"], name="posts_status_bd5975_idx"),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["created_at"], name="posts_created_060265_idx"),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["likes_count"], name="posts_likes_c_1d1075_idx"),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["latitude", "longitude"], name="posts_latitud_e58ecd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="postimage",
            index=models.Index(fields=["post"], name="post_images_post_id_2aae2e_idx"),
        ),
        migrations.AddIndex(
            model_name="postimage",
            index=models.Index(
                fields=["sort_order"], name="post_images_sort_or_b5ec6d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="postlike",
            index=models.Index(
                fields=["post", "user"], name="post_likes_post_id_62cbc8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="postlike",
            index=models.Index(fields=["user"], name="post_likes_user_id_7d46ab_idx"),
        ),
        migrations.AddIndex(
            model_name="postlike",
            index=models.Index(
                fields=["created_at"], name="post_likes_created_c52989_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="postlike",
            unique_together={("post", "user")},
        ),
    ]
