# Generated by Django 5.2.4 on 2025-08-07 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="shop_location",
        ),
    ]
